### PR TITLE
Transform copyright blocks from docstrings into more conventional comments

### PR DESCRIPTION
**Pull request by ydirson**
This is a prereq to applying `futurize`.

### CODE REVIEW

**Comment by lindig** [comment]
I am not familiar with conventions in Python but would have expected that there is a space between the the comment delimiter and the text: so `# comment` rather than `#comment`.

**Comment by ydirson** [comment]
@lindig yes it usually is; I removed the space here to stay in the 80-char-per-line limit, which in turn triggers pylint to complain.  Alternatives I've considered would include reflowing the paragraphs, which is a bit more tricky to script, and raising the line length limit in pylint (as a personal taste I feel that 100 is good enough those days, but YMMV).

**Comment by ydirson** [comment]
Alternatively, as nowadays the SPDX ISO standard is widely recognised and used, the whole license text in each file (not the copyright part, but those lines don't hurt) could be replaced by:
```
# SPDX-License-Identifier: BSD-2-Clause
```

What do you think ?

**Comment by edwintorok** [comment]
I wouldn't mind raising the line length limit to 100 and then we can keep the existing copyright headers just with `#` in front.

**Review by edwintorok — APPROVED** [review]
Thanks, that could work too, but probably best to do a copyright cleanup separately from the python changes, the python changes are quite large already and it is easier to review if we don't need to verify the license of each file.

**Comment by ydirson** [comment]
Firday's push missed changes to subdirs, last push fixes that.

**Review by lindig — APPROVED** [review]

**Comment by ydirson** [comment]
And the last push deals with overlooked licenses in `__init__.py` files.

**Pull request merged**
