### PR TITLE
Testsuite driven py3

### PR DESCRIPTION
**Pull request by ydirson**
Last commits for full python3 compatibility

### CODE REVIEW

**Comment by ydirson** [comment]
Commit "fix xmlunwrap and its test to align with the use of bytes" raises a question, whether we don't want, rather, to fix the `xcp.xmlunwrap` API to use `str` and not `bytes`.

**Comment by ydirson** [comment]
Commit "switch from ConfigParser to configparser" raises a problem with the `Accessor` API, which does not allow to request text or binary streams, which allowed different implementations to return one or the other. Commit "test_accessor: check for I/O on binary files" then proceeds to demonstrate the problem, in the way it will impact `host-upgrade-plugin`.

My opinion is, we should change the Accessor API to add a `mode` parameter to `openAddress()`. Making it mandatory will make sure we don't miss any client code. @edwintorok what do you think ?

**Comment by edwintorok** [comment]
Adding the `mode` parameter seems like the right way forward but it will tie merging and pushing this PR together with other PRs fixing up all users, in that case it might be good to leave that for a 2nd PR so we can merge part of the 2-to-3 conversion without requiring other packages to move or upgrade just yet.

**Comment by ydirson** [comment]
> Adding the `mode` parameter seems like the right way forward but it will tie merging and pushing this PR together with other PRs fixing up all users, in that case it might be good to leave that for a 2nd PR so we can merge part of the 2-to-3 conversion without requiring other packages to move or upgrade just yet.

Yes we could have a separate PR, but this is still part of the 2-to-3 conversion, and requires to push "switch from ConfigParser to configparser" as is, including the workaround for the issue - or just acknowledge that the 2-to-3 work is known not to be complete at this stage and not include the hackish commit, waiting for API refactor.

Similarly for the `xmlunwrap` API issue, which also revolves around `str` vs. `bytes`.

**Comment by bernhardkaindl** [comment]
This PR has been used as the basis of #27 which as been merged to master now, closing as done!

**Pull request closed without merging**
